apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
      - name: init-db
        image: postgres:latest
        env:
        - name: PGPASSWORD
          value: yourpassword
        command: ['sh', '-c', 'psql -h your-db-host -U your-db-user -d your-db-name -f /tmp/seeddb.sql']
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
      containers:
      - name: my-app
        image: my-app-image
        ports:
        - containerPort: 80
      volumes:
      - name: config-volume
        configMap:
          name: db-config